In [15]:
import pandas as pd

In [16]:
real_df = pd.read_csv('../data/real_data.csv', index_col=0)
real_df.drop(['Value', 'Log Value'], inplace=True, axis=1)
real_df.rename(columns={'Scaled Value': 'Value'}, inplace=True)
real_df.index = pd.to_datetime(real_df.index, utc=True)
real_df

,Value,Moving Std,Moving Momentum,Regime,Color
Timestamp,,,,,
2007-01-03 23:45:00+00:00,4700.598978,1114.733391,-1.558889,0.0,g
2007-01-04 00:00:00+00:00,4555.664883,1113.600647,-2.537720,0.0,g
2007-01-04 00:15:00+00:00,4349.762656,1111.906324,-3.739436,0.0,g
2007-01-04 00:30:00+00:00,4346.756464,1109.709744,-4.394472,0.0,g
2007-01-04 00:45:00+00:00,4447.696459,1106.800483,-4.227398,0.0,g
...,...,...,...,...,...
2019-04-30 22:45:00+00:00,1184.442891,852.687300,0.652124,1.0,r
2019-04-30 23:00:00+00:00,1158.571882,852.306562,0.554796,1.0,r
2019-04-30 23:15:00+00:00,1159.896285,851.928142,0.565118,1.0,r
2019-04-30 23:30:00+00:00,1170.661650,851.523117,0.616005,1.0,r
2019-04-30 23:45:00+00:00,1079.617189,851.305432,0.184663,1.0,r

In [17]:
generated_df = pd.read_csv('../data/generated_data.csv', index_col=0)
generated_df.drop(['Moving Avg'], inplace=True, axis=1)
generated_df.index.rename('Timestamp', inplace=True)
generated_df.index = pd.to_datetime(generated_df.index, utc=True)
generated_df

,Value,Moving Std,Moving Momentum,Regime,Color
Timestamp,,,,,
2050-01-06 23:30:00+00:00,550.591313,311.267358,1.195178,0.0,g
2050-01-06 23:45:00+00:00,565.220906,311.044091,1.011736,0.0,g
2050-01-07 00:00:00+00:00,469.550578,310.889411,0.748667,0.0,g
2050-01-07 00:15:00+00:00,440.727372,310.689049,0.571460,0.0,g
2050-01-07 00:30:00+00:00,385.232955,310.551134,0.528588,0.0,g
...,...,...,...,...,...
2061-12-28 23:00:00+00:00,881.572049,624.910895,-6.915853,0.0,g
2061-12-28 23:15:00+00:00,879.706055,614.039962,-6.544867,0.0,g
2061-12-28 23:30:00+00:00,869.721680,604.097090,-6.620069,0.0,g
2061-12-28 23:45:00+00:00,920.833225,593.790683,-6.192217,0.0,g
2061-12-29 00:00:00+00:00,866.976888,584.020453,-6.382588,0.0,g